/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy.view;

import pharmacy.persistence.DB;

/**
 *
 * @author danny
 */
public class FraAboutt extends javax.swing.JFrame {
    private DB dataFile;
    /**
     * Creates new form FraAbout
     */
    public FraAboutt() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    FraAboutt(DB dataFile) {
        initComponents();

        this.setLocationRelativeTo(null);

        this.dataFile = dataFile;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lbMade = new javax.swing.JLabel();
        author1 = new javax.swing.JLabel();
        author2 = new javax.swing.JLabel();
        photoAutor1 = new javax.swing.JLabel();
        photoAutor2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 51));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Application of a pharmacy RaldySalud");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 468, -1));

        lbMade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMade.setText("Application made by:");
        getContentPane().add(lbMade, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        author1.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        author1.setText("Daniel Ricardo Higuera Villamil");
        author1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(author1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        author2.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        author2.setText("Ivan Camilo Rincon Perez");
        author2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(author2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        photoAutor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/view/DanielHiguera.jpg"))); // NOI18N
        getContentPane().add(photoAutor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        photoAutor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/view/CamiloRincon.jpg"))); // NOI18N
        getContentPane().add(photoAutor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/view/fondo-de-pantalla-blanco-2 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FraAboutt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FraAboutt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FraAboutt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FraAboutt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FraAboutt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author1;
    private javax.swing.JLabel author2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbMade;
    private javax.swing.JLabel photoAutor1;
    private javax.swing.JLabel photoAutor2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
