package pharmacy.view;

import pharmacy.persistence.DB;
import javax.swing.JFrame;

/**
 * The BillApp MDI frame
 * @author CR
 */
public class PharmacyMDI extends javax.swing.JFrame {
    private DB dataFile;
    private int userLevel;

    /**
     * Creates new form BillAppMDI
     */
    public PharmacyMDI() {
        //initComponents();
    }

    /**
     * Creates new form BillAppMDI
     * @param dataFile Database file
     * @param userLevel User level
     */
    public PharmacyMDI(DB dataFile, int userLevel) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.dataFile = dataFile;
        this.userLevel = userLevel;
        
        if (userLevel == 1) {
            mnuAdministrator.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDesktop = new javax.swing.JDesktopPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuSell = new javax.swing.JMenuItem();
        mnuAdministrator = new javax.swing.JMenu();
        mnuEmployees = new javax.swing.JMenuItem();
        mnuUsers = new javax.swing.JMenuItem();
        mnuProducts = new javax.swing.JMenuItem();
        mnuSeparator = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuContent = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PharmacyRSApp");

        panDesktop.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        panDesktop.setDoubleBuffered(true);
        panDesktop.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        mnuFile.setMnemonic('f');
        mnuFile.setText("File");

        mnuSell.setMnemonic('o');
        mnuSell.setText("Sell...");
        mnuSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSellActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSell);

        mnuAdministrator.setText("Administrator");

        mnuEmployees.setText("Employees...");
        mnuEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmployeesActionPerformed(evt);
            }
        });
        mnuAdministrator.add(mnuEmployees);

        mnuUsers.setText("Users...");
        mnuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsersActionPerformed(evt);
            }
        });
        mnuAdministrator.add(mnuUsers);

        mnuProducts.setText("Products...");
        mnuProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductsActionPerformed(evt);
            }
        });
        mnuAdministrator.add(mnuProducts);

        mnuFile.add(mnuAdministrator);
        mnuFile.add(mnuSeparator);

        mnuExit.setMnemonic('x');
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        mnuBar.add(mnuFile);

        mnuHelp.setMnemonic('h');
        mnuHelp.setText("Help");
        mnuHelp.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        mnuContent.setMnemonic('c');
        mnuContent.setText("Contents");
        mnuContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuContentActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuContent);

        mnuAbout.setMnemonic('a');
        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        mnuBar.add(mnuHelp);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Application exit
     * @param evt Event
     */
    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    /**
     * Call employees form
     * @param evt 
     */
    private void mnuEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmployeesActionPerformed
        FraEmployee employeeForm = new FraEmployee(this.getDataFile());
        employeeForm.setVisible(true);
    }//GEN-LAST:event_mnuEmployeesActionPerformed

    /**
     * Call users form
     * @param evt Event
     */
    private void mnuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsersActionPerformed
        FraUser userForm = new FraUser(this.getDataFile());
        userForm.setVisible(true);
    }//GEN-LAST:event_mnuUsersActionPerformed

    private void mnuProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductsActionPerformed
        FraProduct productForm = new FraProduct(this.getDataFile());
        productForm.setVisible(true);
    }//GEN-LAST:event_mnuProductsActionPerformed

    private void mnuSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSellActionPerformed
        FraSell saleForm = new FraSell(this.getDataFile());
        saleForm.setVisible(true);
    }//GEN-LAST:event_mnuSellActionPerformed

    private void mnuContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuContentActionPerformed
        FraContents ContentsForm = new FraContents(this.getDataFile());
        ContentsForm.setVisible(true);

    }//GEN-LAST:event_mnuContentActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        FraAboutt aboutForm = new FraAboutt(this.getDataFile());
        aboutForm.setVisible(true);
        
    }//GEN-LAST:event_mnuAboutActionPerformed

    /**
     * Get data file
     * @return data file
     */
    public DB getDataFile() {
        return this.dataFile;
    }

    /**
     * Set data file
     * @param dataFile data file
     */
    public void setDataFile(DB dataFile) {
        this.dataFile = dataFile;
    }

    /**
     * Get User level
     * @return User level
     */
    public int getUserLevel() {
        return this.userLevel;
    }

    /**
     * Set User level
     * @param userLevel User level
     */
    public void setUserLevel(int userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PharmacyMDI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuAdministrator;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuContent;
    private javax.swing.JMenuItem mnuEmployees;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuProducts;
    private javax.swing.JMenuItem mnuSell;
    private javax.swing.JPopupMenu.Separator mnuSeparator;
    private javax.swing.JMenuItem mnuUsers;
    private javax.swing.JDesktopPane panDesktop;
    // End of variables declaration//GEN-END:variables
}
